# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  conbentwebapp:
    image: conbentwebapp
    build:
      context: .
      dockerfile: src/Application/Conbent.WebApp/Dockerfile
    ports:
      - 5286:5286
